; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = t4s3-micropython
src_dir = project
boards_dir = boards

[env:t4s3-micropython]
targets = build_app_fs
platform = espressif32@6.7.0
board = T-Display-AMOLED
upload_speed = 115200
monitor_speed = 115200
upload_protocol = custom
extra_scripts = pre:platformio/deploy.py
platform_packages = 
	platformio/tool-mkfatfs@^2.0.1
	espressif/toolchain-xtensa-esp32s3@12.2.0+20230208
build_src_filter = -<*> +<pio_upload_stub.c>
